version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: VisitTrackerDb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  visittracker-api:
    build:
      context: ./VisitTracker.API
    container_name: visittracker-api
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mysql_data:
